# CMake generated Testfile for 
# Source directory: /home/steven/cfdx_dev
# Build directory: /home/steven/cfdx_dev/build-release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_point "/home/steven/cfdx_dev/build-release/test_point")
set_tests_properties(test_point PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;211;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_face "/home/steven/cfdx_dev/build-release/test_face")
set_tests_properties(test_face PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;212;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_ownership "/home/steven/cfdx_dev/build-release/test_ownership")
set_tests_properties(test_ownership PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;213;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cell "/home/steven/cfdx_dev/build-release/test_cell")
set_tests_properties(test_cell PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;214;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_boundary "/home/steven/cfdx_dev/build-release/test_boundary")
set_tests_properties(test_boundary PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;215;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mesh "/home/steven/cfdx_dev/build-release/test_mesh")
set_tests_properties(test_mesh PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;216;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_field "/home/steven/cfdx_dev/build-release/test_field")
set_tests_properties(test_field PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;217;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_field_storage "/home/steven/cfdx_dev/build-release/test_field_storage")
set_tests_properties(test_field_storage PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;218;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_boundary_field "/home/steven/cfdx_dev/build-release/test_boundary_field")
set_tests_properties(test_boundary_field PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;219;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_interpolation "/home/steven/cfdx_dev/build-release/test_interpolation")
set_tests_properties(test_interpolation PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;220;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_gradient "/home/steven/cfdx_dev/build-release/test_gradient")
set_tests_properties(test_gradient PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;221;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_divergence "/home/steven/cfdx_dev/build-release/test_divergence")
set_tests_properties(test_divergence PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;222;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_flux "/home/steven/cfdx_dev/build-release/test_flux")
set_tests_properties(test_flux PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;223;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_integrate "/home/steven/cfdx_dev/build-release/test_integrate")
set_tests_properties(test_integrate PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;224;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_sparse_matrix "/home/steven/cfdx_dev/build-release/test_sparse_matrix")
set_tests_properties(test_sparse_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;227;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_vector "/home/steven/cfdx_dev/build-release/test_vector")
set_tests_properties(test_vector PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;228;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_linear_system "/home/steven/cfdx_dev/build-release/test_linear_system")
set_tests_properties(test_linear_system PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;229;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cg_solver "/home/steven/cfdx_dev/build-release/test_cg_solver")
set_tests_properties(test_cg_solver PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;230;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_bicgstab_solver "/home/steven/cfdx_dev/build-release/test_bicgstab_solver")
set_tests_properties(test_bicgstab_solver PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;231;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_laplacian "/home/steven/cfdx_dev/build-release/test_laplacian")
set_tests_properties(test_laplacian PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;234;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_face_geometry "/home/steven/cfdx_dev/build-release/test_face_geometry")
set_tests_properties(test_face_geometry PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;237;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cell_geometry "/home/steven/cfdx_dev/build-release/test_cell_geometry")
set_tests_properties(test_cell_geometry PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;238;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mesh_quality "/home/steven/cfdx_dev/build-release/test_mesh_quality")
set_tests_properties(test_mesh_quality PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;239;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_source_term "/home/steven/cfdx_dev/build-release/test_source_term")
set_tests_properties(test_source_term PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;240;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_geometry_cache "/home/steven/cfdx_dev/build-release/test_geometry_cache")
set_tests_properties(test_geometry_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;242;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mpi_partition "/home/steven/cfdx_dev/build-release/test_mpi_partition")
set_tests_properties(test_mpi_partition PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;243;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_transport_models "/home/steven/cfdx_dev/build-release/test_transport_models")
set_tests_properties(test_transport_models PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;244;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_hdf5_writer "/home/steven/cfdx_dev/build-release/test_hdf5_writer")
set_tests_properties(test_hdf5_writer PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;247;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_hdf5_roundtrip "/home/steven/cfdx_dev/build-release/test_hdf5_roundtrip")
set_tests_properties(test_hdf5_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;248;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_field_roundtrip "/home/steven/cfdx_dev/build-release/test_field_roundtrip")
set_tests_properties(test_field_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;249;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_memory_planner_validation "/home/steven/cfdx_dev/build-release/test_memory_planner_validation")
set_tests_properties(test_memory_planner_validation PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;252;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_plan_complet "/home/steven/cfdx_dev/build-release/test_plan_complet")
set_tests_properties(test_plan_complet PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;207;add_test;/home/steven/cfdx_dev/CMakeLists.txt;255;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
