# CMake generated Testfile for 
# Source directory: /home/steven/cfdx_dev
# Build directory: /home/steven/cfdx_dev/build_san
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_point "/home/steven/cfdx_dev/build_san/test_point")
set_tests_properties(test_point PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;182;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_face "/home/steven/cfdx_dev/build_san/test_face")
set_tests_properties(test_face PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;183;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_ownership "/home/steven/cfdx_dev/build_san/test_ownership")
set_tests_properties(test_ownership PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;184;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cell "/home/steven/cfdx_dev/build_san/test_cell")
set_tests_properties(test_cell PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;185;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_boundary "/home/steven/cfdx_dev/build_san/test_boundary")
set_tests_properties(test_boundary PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;186;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mesh "/home/steven/cfdx_dev/build_san/test_mesh")
set_tests_properties(test_mesh PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;187;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_field "/home/steven/cfdx_dev/build_san/test_field")
set_tests_properties(test_field PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;188;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_field_storage "/home/steven/cfdx_dev/build_san/test_field_storage")
set_tests_properties(test_field_storage PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;189;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_boundary_field "/home/steven/cfdx_dev/build_san/test_boundary_field")
set_tests_properties(test_boundary_field PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;190;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_interpolation "/home/steven/cfdx_dev/build_san/test_interpolation")
set_tests_properties(test_interpolation PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;191;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_gradient "/home/steven/cfdx_dev/build_san/test_gradient")
set_tests_properties(test_gradient PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;192;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_divergence "/home/steven/cfdx_dev/build_san/test_divergence")
set_tests_properties(test_divergence PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;193;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_flux "/home/steven/cfdx_dev/build_san/test_flux")
set_tests_properties(test_flux PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;194;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_integrate "/home/steven/cfdx_dev/build_san/test_integrate")
set_tests_properties(test_integrate PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;195;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_sparse_matrix "/home/steven/cfdx_dev/build_san/test_sparse_matrix")
set_tests_properties(test_sparse_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;198;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_vector "/home/steven/cfdx_dev/build_san/test_vector")
set_tests_properties(test_vector PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;199;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_linear_system "/home/steven/cfdx_dev/build_san/test_linear_system")
set_tests_properties(test_linear_system PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;200;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cg_solver "/home/steven/cfdx_dev/build_san/test_cg_solver")
set_tests_properties(test_cg_solver PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;201;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_bicgstab_solver "/home/steven/cfdx_dev/build_san/test_bicgstab_solver")
set_tests_properties(test_bicgstab_solver PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;202;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_laplacian "/home/steven/cfdx_dev/build_san/test_laplacian")
set_tests_properties(test_laplacian PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;205;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_face_geometry "/home/steven/cfdx_dev/build_san/test_face_geometry")
set_tests_properties(test_face_geometry PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;208;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cell_geometry "/home/steven/cfdx_dev/build_san/test_cell_geometry")
set_tests_properties(test_cell_geometry PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;209;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mesh_quality "/home/steven/cfdx_dev/build_san/test_mesh_quality")
set_tests_properties(test_mesh_quality PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;210;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_hdf5_writer "/home/steven/cfdx_dev/build_san/test_hdf5_writer")
set_tests_properties(test_hdf5_writer PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;215;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_hdf5_roundtrip "/home/steven/cfdx_dev/build_san/test_hdf5_roundtrip")
set_tests_properties(test_hdf5_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;216;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_field_roundtrip "/home/steven/cfdx_dev/build_san/test_field_roundtrip")
set_tests_properties(test_field_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;178;add_test;/home/steven/cfdx_dev/CMakeLists.txt;217;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
