# CMake generated Testfile for 
# Source directory: /home/steven/cfdx_dev
# Build directory: /home/steven/cfdx_dev/build-verify
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_n8_physical_qualification "/home/steven/venv/bin/python3.10" "/home/steven/cfdx_dev/scripts/n8_physical_qualification.py" "--build-dir" "/home/steven/cfdx_dev/build-verify")
set_tests_properties(test_n8_physical_qualification PROPERTIES  LABELS "n8;qualification;validation" RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;417;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_point "/home/steven/cfdx_dev/build-verify/test_point")
set_tests_properties(test_point PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;427;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_face "/home/steven/cfdx_dev/build-verify/test_face")
set_tests_properties(test_face PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;428;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_ownership "/home/steven/cfdx_dev/build-verify/test_ownership")
set_tests_properties(test_ownership PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;429;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cell "/home/steven/cfdx_dev/build-verify/test_cell")
set_tests_properties(test_cell PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;430;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_boundary "/home/steven/cfdx_dev/build-verify/test_boundary")
set_tests_properties(test_boundary PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;431;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mesh "/home/steven/cfdx_dev/build-verify/test_mesh")
set_tests_properties(test_mesh PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;432;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_field "/home/steven/cfdx_dev/build-verify/test_field")
set_tests_properties(test_field PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;433;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_field_storage "/home/steven/cfdx_dev/build-verify/test_field_storage")
set_tests_properties(test_field_storage PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;434;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_field_wall_hardening "/home/steven/cfdx_dev/build-verify/test_field_wall_hardening")
set_tests_properties(test_field_wall_hardening PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;435;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_boundary_field "/home/steven/cfdx_dev/build-verify/test_boundary_field")
set_tests_properties(test_boundary_field PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;436;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_boundary_contract "/home/steven/cfdx_dev/build-verify/test_boundary_contract")
set_tests_properties(test_boundary_contract PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;437;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_boundary_fvm_constraints "/home/steven/cfdx_dev/build-verify/test_boundary_fvm_constraints")
set_tests_properties(test_boundary_fvm_constraints PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;438;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_boundary_validator "/home/steven/cfdx_dev/build-verify/test_boundary_validator")
set_tests_properties(test_boundary_validator PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;439;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_interpolation "/home/steven/cfdx_dev/build-verify/test_interpolation")
set_tests_properties(test_interpolation PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;440;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_gradient "/home/steven/cfdx_dev/build-verify/test_gradient")
set_tests_properties(test_gradient PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;441;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_pressure_velocity_system "/home/steven/cfdx_dev/build-verify/test_pressure_velocity_system")
set_tests_properties(test_pressure_velocity_system PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;442;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_oriented_numerics "/home/steven/cfdx_dev/build-verify/test_oriented_numerics")
set_tests_properties(test_oriented_numerics PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;443;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_divergence "/home/steven/cfdx_dev/build-verify/test_divergence")
set_tests_properties(test_divergence PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;444;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_flux "/home/steven/cfdx_dev/build-verify/test_flux")
set_tests_properties(test_flux PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;445;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_spatial_scheme_contract "/home/steven/cfdx_dev/build-verify/test_spatial_scheme_contract")
set_tests_properties(test_spatial_scheme_contract PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;446;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_conservation_boundedness "/home/steven/cfdx_dev/build-verify/test_conservation_boundedness")
set_tests_properties(test_conservation_boundedness PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;447;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_transport_conservation "/home/steven/cfdx_dev/build-verify/test_transport_conservation")
set_tests_properties(test_transport_conservation PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;448;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_conservation_assembly "/home/steven/cfdx_dev/build-verify/test_conservation_assembly")
set_tests_properties(test_conservation_assembly PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;449;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_integrate "/home/steven/cfdx_dev/build-verify/test_integrate")
set_tests_properties(test_integrate PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;450;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_forces "/home/steven/cfdx_dev/build-verify/test_forces")
set_tests_properties(test_forces PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;451;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_sparse_matrix "/home/steven/cfdx_dev/build-verify/test_sparse_matrix")
set_tests_properties(test_sparse_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;454;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_vector "/home/steven/cfdx_dev/build-verify/test_vector")
set_tests_properties(test_vector PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;455;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_linear_system "/home/steven/cfdx_dev/build-verify/test_linear_system")
set_tests_properties(test_linear_system PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;456;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cg_solver "/home/steven/cfdx_dev/build-verify/test_cg_solver")
set_tests_properties(test_cg_solver PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;457;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_null_space "/home/steven/cfdx_dev/build-verify/test_null_space")
set_tests_properties(test_null_space PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;458;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_bicgstab_solver "/home/steven/cfdx_dev/build-verify/test_bicgstab_solver")
set_tests_properties(test_bicgstab_solver PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;459;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_gmres_solver "/home/steven/cfdx_dev/build-verify/test_gmres_solver")
set_tests_properties(test_gmres_solver PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;460;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_fgmres_solver "/home/steven/cfdx_dev/build-verify/test_fgmres_solver")
set_tests_properties(test_fgmres_solver PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;461;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_krylov_preconditioning "/home/steven/cfdx_dev/build-verify/test_krylov_preconditioning")
set_tests_properties(test_krylov_preconditioning PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;462;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_stationary_solvers "/home/steven/cfdx_dev/build-verify/test_stationary_solvers")
set_tests_properties(test_stationary_solvers PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;463;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_performance_foundations "/home/steven/cfdx_dev/build-verify/test_performance_foundations")
set_tests_properties(test_performance_foundations PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;464;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_performance_runtime "/home/steven/cfdx_dev/build-verify/test_performance_runtime")
set_tests_properties(test_performance_runtime PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;465;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_phase6_memory_benchmark "/home/steven/cfdx_dev/build-verify/test_phase6_memory_benchmark")
set_tests_properties(test_phase6_memory_benchmark PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;466;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_amg_chebyshev "/home/steven/cfdx_dev/build-verify/test_amg_chebyshev")
set_tests_properties(test_amg_chebyshev PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;467;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_native_external_methods "/home/steven/cfdx_dev/build-verify/test_native_external_methods")
set_tests_properties(test_native_external_methods PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;468;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_amg_preconditioner_qualification "/home/steven/cfdx_dev/build-verify/test_amg_preconditioner_qualification")
set_tests_properties(test_amg_preconditioner_qualification PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;469;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_matrix_free_fv_operator "/home/steven/cfdx_dev/build-verify/test_matrix_free_fv_operator")
set_tests_properties(test_matrix_free_fv_operator PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;470;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_backend_equivalence "/home/steven/cfdx_dev/build-verify/test_backend_equivalence")
set_tests_properties(test_backend_equivalence PROPERTIES  LABELS "phase13;validation;n13" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;471;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_n13_restart_equivalence "/home/steven/cfdx_dev/build-verify/test_n13_restart_equivalence")
set_tests_properties(test_n13_restart_equivalence PROPERTIES  LABELS "phase13;validation;n13" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;474;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_laplacian "/home/steven/cfdx_dev/build-verify/test_laplacian")
set_tests_properties(test_laplacian PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;477;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_diffusion_diagnostics "/home/steven/cfdx_dev/build-verify/test_diffusion_diagnostics")
set_tests_properties(test_diffusion_diagnostics PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;478;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_phase123_regression "/home/steven/cfdx_dev/build-verify/test_phase123_regression")
set_tests_properties(test_phase123_regression PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;479;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_phase12_radiation_vv "/home/steven/cfdx_dev/build-verify/test_phase12_radiation_vv")
set_tests_properties(test_phase12_radiation_vv PROPERTIES  LABELS "phase12;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;480;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_scalar_diffusion "/home/steven/cfdx_dev/build-verify/test_scalar_diffusion")
set_tests_properties(test_scalar_diffusion PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;482;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_advanced_preconditioners "/home/steven/cfdx_dev/build-verify/test_advanced_preconditioners")
set_tests_properties(test_advanced_preconditioners PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;483;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_schur_preconditioner "/home/steven/cfdx_dev/build-verify/test_schur_preconditioner")
set_tests_properties(test_schur_preconditioner PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;484;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_face_geometry "/home/steven/cfdx_dev/build-verify/test_face_geometry")
set_tests_properties(test_face_geometry PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;487;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cell_geometry "/home/steven/cfdx_dev/build-verify/test_cell_geometry")
set_tests_properties(test_cell_geometry PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;488;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mesh_quality "/home/steven/cfdx_dev/build-verify/test_mesh_quality")
set_tests_properties(test_mesh_quality PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;489;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_geometry_invariants "/home/steven/cfdx_dev/build-verify/test_geometry_invariants")
set_tests_properties(test_geometry_invariants PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;490;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mesh_family_volumes "/home/steven/cfdx_dev/build-verify/test_mesh_family_volumes")
set_tests_properties(test_mesh_family_volumes PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;491;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_source_term "/home/steven/cfdx_dev/build-verify/test_source_term")
set_tests_properties(test_source_term PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;492;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_temporal_physics "/home/steven/cfdx_dev/build-verify/test_temporal_physics")
set_tests_properties(test_temporal_physics PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;493;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_dual_time_stepping "/home/steven/cfdx_dev/build-verify/test_dual_time_stepping")
set_tests_properties(test_dual_time_stepping PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;494;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_dual_time_adaptive "/home/steven/cfdx_dev/build-verify/test_dual_time_adaptive")
set_tests_properties(test_dual_time_adaptive PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;495;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_dual_time_field_driver "/home/steven/cfdx_dev/build-verify/test_dual_time_field_driver")
set_tests_properties(test_dual_time_field_driver PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;496;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_dual_time_field_integrator "/home/steven/cfdx_dev/build-verify/test_dual_time_field_integrator")
set_tests_properties(test_dual_time_field_integrator PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;497;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_dual_time_physical_lifecycle "/home/steven/cfdx_dev/build-verify/test_dual_time_physical_lifecycle")
set_tests_properties(test_dual_time_physical_lifecycle PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;498;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_dual_time_navier_stokes "/home/steven/cfdx_dev/build-verify/test_dual_time_navier_stokes")
set_tests_properties(test_dual_time_navier_stokes PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;499;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_case_numerics_report "/home/steven/cfdx_dev/build-verify/test_case_numerics_report")
set_tests_properties(test_case_numerics_report PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;500;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_temporal_history "/home/steven/cfdx_dev/build-verify/test_temporal_history")
set_tests_properties(test_temporal_history PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;501;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_core_temporal "/home/steven/cfdx_dev/build-verify/test_core_temporal")
set_tests_properties(test_core_temporal PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;502;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_newton_field "/home/steven/cfdx_dev/build-verify/test_newton_field")
set_tests_properties(test_newton_field PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;503;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_simulation_controller "/home/steven/cfdx_dev/build-verify/test_simulation_controller")
set_tests_properties(test_simulation_controller PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;504;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_adaptive_cfl "/home/steven/cfdx_dev/build-verify/test_adaptive_cfl")
set_tests_properties(test_adaptive_cfl PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;505;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_timestep_control "/home/steven/cfdx_dev/build-verify/test_timestep_control")
set_tests_properties(test_timestep_control PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;506;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_continuation "/home/steven/cfdx_dev/build-verify/test_continuation")
set_tests_properties(test_continuation PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;507;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_local_time_stepping "/home/steven/cfdx_dev/build-verify/test_local_time_stepping")
set_tests_properties(test_local_time_stepping PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;508;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_incompressible "/home/steven/cfdx_dev/build-verify/test_incompressible")
set_tests_properties(test_incompressible PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;509;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_m1_m4_physics "/home/steven/cfdx_dev/build-verify/test_m1_m4_physics")
set_tests_properties(test_m1_m4_physics PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;510;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_m1_m4_validation "/home/steven/cfdx_dev/build-verify/test_m1_m4_validation")
set_tests_properties(test_m1_m4_validation PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;511;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_solver_control "/home/steven/cfdx_dev/build-verify/test_solver_control")
set_tests_properties(test_solver_control PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;512;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_convergence_monitor "/home/steven/cfdx_dev/build-verify/test_convergence_monitor")
set_tests_properties(test_convergence_monitor PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;513;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_initialization "/home/steven/cfdx_dev/build-verify/test_initialization")
set_tests_properties(test_initialization PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;514;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_n7_convergence_qualification "/home/steven/cfdx_dev/build-verify/test_n7_convergence_qualification")
set_tests_properties(test_n7_convergence_qualification PROPERTIES  LABELS "n7;qualification;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;518;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_finite_volume_transport "/home/steven/cfdx_dev/build-verify/test_finite_volume_transport")
set_tests_properties(test_finite_volume_transport PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;521;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_steady_incompressible_solver "/home/steven/cfdx_dev/build-verify/test_steady_incompressible_solver")
set_tests_properties(test_steady_incompressible_solver PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;522;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_vtu_writer_validation "/home/steven/cfdx_dev/build-verify/test_vtu_writer_validation")
set_tests_properties(test_vtu_writer_validation PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;523;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_solver_vtu_provenance "/home/steven/cfdx_dev/build-verify/test_solver_vtu_provenance")
set_tests_properties(test_solver_vtu_provenance PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;524;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_ghia_cavity_quick "/home/steven/cfdx_dev/build-verify/test_ghia_cavity" "--quick")
set_tests_properties(test_ghia_cavity_quick PROPERTIES  LABELS "qualification;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;528;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_ghia_cavity_order "/home/steven/cfdx_dev/build-verify/test_ghia_cavity" "--gate")
set_tests_properties(test_ghia_cavity_order PROPERTIES  LABELS "phase13;validation;campaign" TIMEOUT "900" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;535;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_n8_pressure_velocity_matrix "/home/steven/cfdx_dev/build-verify/test_phase9_acceptance")
set_tests_properties(test_n8_pressure_velocity_matrix PROPERTIES  LABELS "n8;qualification;validation" RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;549;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_couette_quick "/home/steven/cfdx_dev/build-verify/test_phase9_acceptance" "--quick")
set_tests_properties(test_couette_quick PROPERTIES  ENVIRONMENT "CFDX_DEBUG_CELL=33;CFDX_FREEZE_STATE=1;CFDX_DEBUG_COUPLED=1" LABELS "qualification;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;553;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_m2_m4_solver_validation "/home/steven/cfdx_dev/build-verify/test_m2_m4_solver_validation")
set_tests_properties(test_m2_m4_solver_validation PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;567;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_phase10_turbulence_hardening "/home/steven/cfdx_dev/build-verify/test_phase10_turbulence_hardening")
set_tests_properties(test_phase10_turbulence_hardening PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;568;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_turbulence_qualification_equations "/home/steven/cfdx_dev/build-verify/test_turbulence_qualification_equations")
set_tests_properties(test_turbulence_qualification_equations PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;569;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_phase10_model_registry "/home/steven/cfdx_dev/build-verify/test_phase10_model_registry")
set_tests_properties(test_phase10_model_registry PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;570;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_wall_distance_methods "/home/steven/cfdx_dev/build-verify/test_wall_distance_methods")
set_tests_properties(test_wall_distance_methods PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;571;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(benchmark_wall_distance_complex "/home/steven/cfdx_dev/build-verify/cfdx_wall_distance_complex_benchmark" "/home/steven/cfdx_dev/build-verify/wall_distance_complex_benchmark.csv")
set_tests_properties(benchmark_wall_distance_complex PROPERTIES  LABELS "phase13;validation;benchmark" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;572;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_phase10_sst_limiter "/home/steven/cfdx_dev/build-verify/test_phase10_sst_limiter")
set_tests_properties(test_phase10_sst_limiter PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;575;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_analytical_benchmarks "/home/steven/cfdx_dev/build-verify/test_analytical_benchmarks")
set_tests_properties(test_analytical_benchmarks PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;576;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_vmfl036_reference_case "/home/steven/cfdx_dev/build-verify/test_vmfl036_reference_case")
set_tests_properties(test_vmfl036_reference_case PROPERTIES  LABELS "phase14;validation;reference" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;577;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_axisymmetric_vmfl036_kernel "/home/steven/cfdx_dev/build-verify/test_axisymmetric_vmfl036_kernel")
set_tests_properties(test_axisymmetric_vmfl036_kernel PROPERTIES  LABELS "phase14;validation;axisymmetric" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;578;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_vmfl036_axisymmetric_quick "/home/steven/cfdx_dev/build-verify/test_vmfl036_axisymmetric" "--quick")
set_tests_properties(test_vmfl036_axisymmetric_quick PROPERTIES  LABELS "phase14;validation;axisymmetric" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;586;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_bfs_quick "/home/steven/cfdx_dev/build-verify/test_bfs_qualification" "--quick" "/home/steven/cfdx_dev/build-verify/validation_meshes/bfs_re200_n16.h5")
set_tests_properties(test_bfs_quick PROPERTIES  DEPENDS "test_generate_2d_validation_meshes" LABELS "qualification;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;604;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_naca0012_quick "/home/steven/cfdx_dev/build-verify/test_naca0012_qualification" "--quick" "/home/steven/cfdx_dev/build-verify/validation_meshes/naca0012_laminar_n64.h5")
set_tests_properties(test_naca0012_quick PROPERTIES  DEPENDS "test_generate_2d_validation_meshes" LABELS "qualification;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;608;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_generate_2d_validation_meshes "/home/steven/venv/bin/python3.10" "/home/steven/cfdx_dev/scripts/generate_2d_validation_meshes.py" "all" "--output-dir" "/home/steven/cfdx_dev/build-verify/validation_meshes")
set_tests_properties(test_generate_2d_validation_meshes PROPERTIES  LABELS "qualification;mesh;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;623;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_channel_quick "/home/steven/cfdx_dev/build-verify/test_channel_qualification" "--quick" "/home/steven/cfdx_dev/build-verify/validation_meshes/channel_n16.h5")
set_tests_properties(test_channel_quick PROPERTIES  DEPENDS "test_generate_2d_validation_meshes" LABELS "qualification;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;629;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_numerical_model_verification "/home/steven/cfdx_dev/build-verify/test_numerical_model_verification")
set_tests_properties(test_numerical_model_verification PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;641;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_poiseuille_quick "/home/steven/cfdx_dev/build-verify/test_poiseuille_diagnostics" "--quick")
set_tests_properties(test_poiseuille_quick PROPERTIES  LABELS "qualification;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;645;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mms_scalar_diffusion "/home/steven/cfdx_dev/build-verify/test_mms_scalar_diffusion")
set_tests_properties(test_mms_scalar_diffusion PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;653;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_nonorthogonal_skew_campaign "/home/steven/cfdx_dev/build-verify/test_nonorthogonal_skew_campaign")
set_tests_properties(test_nonorthogonal_skew_campaign PROPERTIES  LABELS "validation;qualification;n10" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;662;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_nonorthogonal_laplacian_campaign "/home/steven/cfdx_dev/build-verify/test_nonorthogonal_laplacian_campaign")
set_tests_properties(test_nonorthogonal_laplacian_campaign PROPERTIES  LABELS "validation;qualification;n10" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;663;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_transient_mms "/home/steven/cfdx_dev/build-verify/test_transient_mms")
set_tests_properties(test_transient_mms PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;664;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_transient_mms_closure "/home/steven/cfdx_dev/build-verify/test_transient_mms_closure")
set_tests_properties(test_transient_mms_closure PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;665;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_transient_mms_3d_stiff "/home/steven/cfdx_dev/build-verify/test_transient_mms_3d_stiff")
set_tests_properties(test_transient_mms_3d_stiff PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;666;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_polyhedral_laplacian_campaign "/home/steven/cfdx_dev/build-verify/test_polyhedral_laplacian_campaign")
set_tests_properties(test_polyhedral_laplacian_campaign PROPERTIES  LABELS "validation;qualification;n10" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;667;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_convection_scheme_verification "/home/steven/cfdx_dev/build-verify/test_convection_scheme_verification")
set_tests_properties(test_convection_scheme_verification PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;668;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_convection_3d_verification "/home/steven/cfdx_dev/build-verify/test_convection_3d_verification")
set_tests_properties(test_convection_3d_verification PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;669;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_convection_blending "/home/steven/cfdx_dev/build-verify/test_convection_blending")
set_tests_properties(test_convection_blending PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;670;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_n16_weno5z "/home/steven/cfdx_dev/build-verify/test_n16_weno5z")
set_tests_properties(test_n16_weno5z PROPERTIES  LABELS "n16;validation;experimental" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;671;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_temporal_order_matrix "/home/steven/cfdx_dev/build-verify/test_temporal_order_matrix")
set_tests_properties(test_temporal_order_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;673;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_gradient_verification "/home/steven/cfdx_dev/build-verify/test_gradient_verification")
set_tests_properties(test_gradient_verification PROPERTIES  LABELS "validation;qualification;n10" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;674;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_polyhedral_gradient_campaign "/home/steven/cfdx_dev/build-verify/test_polyhedral_gradient_campaign")
set_tests_properties(test_polyhedral_gradient_campaign PROPERTIES  LABELS "validation;qualification;n10" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;675;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_n10_difficult_mesh_robustness "/home/steven/cfdx_dev/build-verify/test_n10_difficult_mesh_robustness")
set_tests_properties(test_n10_difficult_mesh_robustness PROPERTIES  LABELS "validation;qualification;n10" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;676;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_convection_polyhedral_campaign "/home/steven/cfdx_dev/build-verify/test_convection_polyhedral_campaign")
set_tests_properties(test_convection_polyhedral_campaign PROPERTIES  LABELS "phase13;validation;qualification" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;685;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_convection_solver_qualification "/home/steven/cfdx_dev/build-verify/test_convection_solver_qualification")
set_tests_properties(test_convection_solver_qualification PROPERTIES  LABELS "phase13;validation;qualification" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;686;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_fluent_vmfl_reference "/home/steven/cfdx_dev/build-verify/test_fluent_vmfl_reference")
set_tests_properties(test_fluent_vmfl_reference PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;689;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_benchmark_matrix "/home/steven/cfdx_dev/build-verify/test_benchmark_matrix")
set_tests_properties(test_benchmark_matrix PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;690;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_level_b_reference_benchmarks "/home/steven/cfdx_dev/build-verify/test_level_b_reference_benchmarks")
set_tests_properties(test_level_b_reference_benchmarks PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;691;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_level_c_coupled_verification "/home/steven/cfdx_dev/build-verify/test_level_c_coupled_verification")
set_tests_properties(test_level_c_coupled_verification PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;692;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cht_validation "/home/steven/cfdx_dev/build-verify/test_cht_validation")
set_tests_properties(test_cht_validation PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;697;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_thermal_vv "/home/steven/cfdx_dev/build-verify/test_thermal_vv")
set_tests_properties(test_thermal_vv PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;698;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_radiation_vv "/home/steven/cfdx_dev/build-verify/test_radiation_vv")
set_tests_properties(test_radiation_vv PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;699;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_s2s_radiation_vv "/home/steven/cfdx_dev/build-verify/test_s2s_radiation_vv")
set_tests_properties(test_s2s_radiation_vv PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;700;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_thermal_radiation_model_matrix "/home/steven/cfdx_dev/build-verify/test_thermal_radiation_model_matrix")
set_tests_properties(test_thermal_radiation_model_matrix PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;701;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_thermal_radiation_regression "/home/steven/cfdx_dev/build-verify/test_thermal_radiation_regression")
set_tests_properties(test_thermal_radiation_regression PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;702;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_thermal_challenge_vv "/home/steven/cfdx_dev/build-verify/test_thermal_challenge_vv")
set_tests_properties(test_thermal_challenge_vv PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;703;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_thermophysical_models_vv "/home/steven/cfdx_dev/build-verify/test_thermophysical_models_vv")
set_tests_properties(test_thermophysical_models_vv PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;704;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_turbulence_qualification_matrix "/home/steven/venv/bin/python3.10" "/home/steven/cfdx_dev/scripts/validate_turbulence_qualification_matrix.py" "/home/steven/cfdx_dev/docs/validation/TURBULENCE_QUALIFICATION_MATRIX.json")
set_tests_properties(test_turbulence_qualification_matrix PROPERTIES  LABELS "qualification;validation;turbulence" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;716;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cfdx_qualification_registry "/home/steven/venv/bin/python3.10" "/home/steven/cfdx_dev/scripts/validate_qualification_registry.py" "/home/steven/cfdx_dev/docs/validation/CFDX_QUALIFICATION_REGISTRY.json")
set_tests_properties(test_cfdx_qualification_registry PROPERTIES  LABELS "qualification;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;726;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_n13_cuda_equivalence "/home/steven/cfdx_dev/build-verify/test_n13_cuda_equivalence")
set_tests_properties(test_n13_cuda_equivalence PROPERTIES  LABELS "phase13;validation;n13;hardware" SKIP_RETURN_CODE "2" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;735;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_schur_infrastructure "/home/steven/cfdx_dev/build-verify/test_schur_infrastructure")
set_tests_properties(test_schur_infrastructure PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;749;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_exact_schur "/home/steven/cfdx_dev/build-verify/test_exact_schur")
set_tests_properties(test_exact_schur PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;750;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_n9_schur_oracle "/home/steven/cfdx_dev/build-verify/test_n9_schur_oracle")
set_tests_properties(test_n9_schur_oracle PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;751;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_simplerc_schur "/home/steven/cfdx_dev/build-verify/test_simplerc_schur")
set_tests_properties(test_simplerc_schur PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;752;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_lsc_bfbt_schur "/home/steven/cfdx_dev/build-verify/test_lsc_bfbt_schur")
set_tests_properties(test_lsc_bfbt_schur PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;753;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_lsc_bfbt_schur_null_space "/home/steven/cfdx_dev/build-verify/test_lsc_bfbt_schur_null_space")
set_tests_properties(test_lsc_bfbt_schur_null_space PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;754;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_schur_approximation_comparison "/home/steven/cfdx_dev/build-verify/test_schur_approximation_comparison")
set_tests_properties(test_schur_approximation_comparison PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;755;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_schur_quantitative_qualification "/home/steven/cfdx_dev/build-verify/test_schur_quantitative_qualification")
set_tests_properties(test_schur_quantitative_qualification PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;756;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mgr_preconditioner "/home/steven/cfdx_dev/build-verify/test_mgr_preconditioner")
set_tests_properties(test_mgr_preconditioner PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;757;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_wall_distance_turbulence "/home/steven/cfdx_dev/build-verify/test_wall_distance_turbulence")
set_tests_properties(test_wall_distance_turbulence PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;758;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_geometry_cache "/home/steven/cfdx_dev/build-verify/test_geometry_cache")
set_tests_properties(test_geometry_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;759;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_coupled_block_schur_amg "/home/steven/cfdx_dev/build-verify/test_coupled_block_schur_amg")
set_tests_properties(test_coupled_block_schur_amg PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;760;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_n8_schur_production_benchmark "/home/steven/cfdx_dev/build-verify/test_n8_schur_production_benchmark")
set_tests_properties(test_n8_schur_production_benchmark PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;761;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mpi_deterministic "/usr/bin/mpiexec" "-n" "2" "/home/steven/cfdx_dev/build-verify/test_mpi_deterministic")
set_tests_properties(test_mpi_deterministic PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;796;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_n13_mpi_equivalence "/usr/bin/mpiexec" "-n" "2" "/home/steven/cfdx_dev/build-verify/test_n13_mpi_equivalence")
set_tests_properties(test_n13_mpi_equivalence PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/home/steven/cfdx_dev/tests/sanitizers/lsan_mpi.supp" LABELS "phase13;validation;n13" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;799;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mpi_partition "/usr/bin/mpiexec" "-n" "2" "/home/steven/cfdx_dev/build-verify/test_mpi_partition")
set_tests_properties(test_mpi_partition PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;805;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mpi_fused_reduction "/usr/bin/mpiexec" "-n" "2" "/home/steven/cfdx_dev/build-verify/test_mpi_fused_reduction")
set_tests_properties(test_mpi_fused_reduction PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;808;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mpi_krylov_reduction "/usr/bin/mpiexec" "-n" "2" "/home/steven/cfdx_dev/build-verify/test_mpi_krylov_reduction")
set_tests_properties(test_mpi_krylov_reduction PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;811;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_phase8_mpi_poisson "/usr/bin/mpiexec" "-n" "2" "/home/steven/cfdx_dev/build-verify/test_phase8_mpi_poisson")
set_tests_properties(test_phase8_mpi_poisson PROPERTIES  LABELS "phase13;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;814;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_restart_mapping "/home/steven/cfdx_dev/build-verify/test_restart_mapping")
set_tests_properties(test_restart_mapping PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;861;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_transport_models "/home/steven/cfdx_dev/build-verify/test_transport_models")
set_tests_properties(test_transport_models PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;862;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_equation_of_state_consistency "/home/steven/cfdx_dev/build-verify/test_equation_of_state_consistency")
set_tests_properties(test_equation_of_state_consistency PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;863;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_sst_blending "/home/steven/cfdx_dev/build-verify/test_sst_blending")
set_tests_properties(test_sst_blending PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;864;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_thermo_transport_contracts "/home/steven/cfdx_dev/build-verify/test_thermo_transport_contracts")
set_tests_properties(test_thermo_transport_contracts PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;865;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_thermophysical_models "/home/steven/cfdx_dev/build-verify/test_thermophysical_models")
set_tests_properties(test_thermophysical_models PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;866;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_m5_m7_foundations "/home/steven/cfdx_dev/build-verify/test_m5_m7_foundations")
set_tests_properties(test_m5_m7_foundations PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;867;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_runtime_execution_ooc "/home/steven/cfdx_dev/build-verify/test_runtime_execution_ooc")
set_tests_properties(test_runtime_execution_ooc PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;869;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_runtime_pipeline "/home/steven/cfdx_dev/build-verify/test_runtime_pipeline")
set_tests_properties(test_runtime_pipeline PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;870;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_phase6_runtime_acceptance "/home/steven/cfdx_dev/build-verify/test_phase6_runtime_acceptance")
set_tests_properties(test_phase6_runtime_acceptance PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;871;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_ooc_pipeline "/home/steven/cfdx_dev/build-verify/test_ooc_pipeline")
set_tests_properties(test_ooc_pipeline PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;872;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_phase7_ooc_validation "/home/steven/cfdx_dev/build-verify/test_phase7_ooc_validation")
set_tests_properties(test_phase7_ooc_validation PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;873;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_hdf5_writer "/home/steven/cfdx_dev/build-verify/test_hdf5_writer")
set_tests_properties(test_hdf5_writer PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;882;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_hdf5_roundtrip "/home/steven/cfdx_dev/build-verify/test_hdf5_roundtrip")
set_tests_properties(test_hdf5_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;883;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_field_roundtrip "/home/steven/cfdx_dev/build-verify/test_field_roundtrip")
set_tests_properties(test_field_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;884;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_case_hdf5_io "/home/steven/cfdx_dev/build-verify/test_case_hdf5_io")
set_tests_properties(test_case_hdf5_io PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;885;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_memory_planner_validation "/home/steven/cfdx_dev/build-verify/test_memory_planner_validation")
set_tests_properties(test_memory_planner_validation PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;891;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_plan_complet "/home/steven/cfdx_dev/build-verify/test_plan_complet")
set_tests_properties(test_plan_complet PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;894;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_validation_simple "/home/steven/cfdx_dev/build-verify/test_validation_simple")
set_tests_properties(test_validation_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;897;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_openfoam_importer "/home/steven/cfdx_dev/build-verify/test_openfoam_importer")
set_tests_properties(test_openfoam_importer PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;898;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_cross_import_equivalence "/home/steven/cfdx_dev/build-verify/test_cross_import_equivalence")
set_tests_properties(test_cross_import_equivalence PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;900;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_missing_qualification_case_contracts "/home/steven/venv/bin/python3.10" "/home/steven/cfdx_dev/scripts/test_missing_qualification_case_contracts.py")
set_tests_properties(test_missing_qualification_case_contracts PROPERTIES  LABELS "qualification;validation" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;903;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_production_solver_e2e "/home/steven/venv/bin/python3.10" "/home/steven/cfdx_dev/tests/python/test_production_solver_e2e.py")
set_tests_properties(test_production_solver_e2e PROPERTIES  ENVIRONMENT "CFDX_PRODUCTION_SOLVER=/home/steven/cfdx_dev/build-verify/cfdx_production_solver;CFDX_PRODUCTION_MESH=/home/steven/cfdx_dev/tests/data/cavity_with_patches.msh;PYTHONPATH=/home/steven/cfdx_dev/src/cfdx/python" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;909;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_production_solver_numerics_e2e "/home/steven/venv/bin/python3.10" "/home/steven/cfdx_dev/tests/python/test_production_solver_numerics_e2e.py")
set_tests_properties(test_production_solver_numerics_e2e PROPERTIES  ENVIRONMENT "CFDX_PRODUCTION_SOLVER=/home/steven/cfdx_dev/build-verify/cfdx_production_solver;PYTHONPATH=/home/steven/cfdx_dev/src/cfdx/python" _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;914;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_meshio_bridge "/home/steven/venv/bin/python3.10" "/home/steven/cfdx_dev/tests/mesh/test_meshio_bridge.py" "/home/steven/cfdx_dev/scripts/meshio_import.py")
set_tests_properties(test_meshio_bridge PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;920;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_mesh_geometry_matrix "/home/steven/venv/bin/python3.10" "/home/steven/cfdx_dev/tests/mesh/test_mesh_geometry_matrix.py" "/home/steven/cfdx_dev/scripts/meshio_import.py")
set_tests_properties(test_mesh_geometry_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;924;add_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
add_test(test_gap_analysis "/home/steven/cfdx_dev/build-verify/test_gap_analysis")
set_tests_properties(test_gap_analysis PROPERTIES  _BACKTRACE_TRIPLES "/home/steven/cfdx_dev/CMakeLists.txt;409;add_test;/home/steven/cfdx_dev/CMakeLists.txt;932;add_cfdx_test;/home/steven/cfdx_dev/CMakeLists.txt;0;")
